title: Personal Cat Collection
author: @amirmasoudabdol
email: cat@collection.cat
description: Here is all about cats

# social links
twitter_username: amirmasoudabdol
github_username: amirmasoudabdol

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
